import { randomUUID } from 'node:crypto';
import { Hono } from 'hono';
import { conversationItemInputSchema, toolCallRequestSchema } from '@tooled-voice/shared';
import { and, asc, desc, eq, sql } from 'drizzle-orm';
import { verifyAccessToken } from '../auth/verify-access-token.js';
import { createDatabase } from '../database/client.js';
import { normalizeError } from '../errors/api-error.js';
import { conversationItems, conversations, userProfiles } from '../database/schema.js';
import { logger } from '../logging/logger.js';
import { createRealtimeSession } from '../realtime/create-session.js';
import { dispatchTool } from '../tools/dispatch.js';
type Variables={user:Awaited<ReturnType<typeof verifyAccessToken>>;requestId:string};
export function createApp(database=createDatabase()) {
  const app=new Hono<{Variables:Variables}>();
  app.get('/auth/confirmed',c=>c.html('<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account confirmed</title><body style="background:#11130e;color:#f0f1e8;font:16px system-ui;margin:0;display:grid;min-height:100vh;place-items:center"><main style="padding:32px;max-width:520px"><p style="color:#e8ff58;font-weight:800;letter-spacing:.16em">TOOLED / VOICE</p><h1>Account confirmed.</h1><p>You can return to the Tooled Voice app and sign in.</p></main></body></html>'));
  app.get('/api/health',async c=>{try{await database.execute(sql`select 1`);return c.json({ok:true,database:'connected'})}catch{return c.json({ok:false,database:'unavailable'},503)}});
  app.use('/api/*',async(c,next)=>{const requestId=c.req.header('x-request-id') ?? randomUUID(); c.set('requestId',requestId); c.header('x-request-id',requestId); try { c.set('user',await verifyAccessToken(c.req.header('authorization'))); await next(); } catch(error) { const normalized=normalizeError(error); return c.json({ok:false,error:{code:normalized.code,message:normalized.message,retryable:normalized.retryable}},normalized.status as 401); }});
  app.post('/api/realtime/session',async c=>{try{const userId=c.var.user.id;const body=await c.req.json().catch(()=>({})) as {conversationId?:unknown};await database.insert(userProfiles).values({id:userId}).onConflictDoNothing();const session=await createRealtimeSession(userId,c.req.raw.signal);let conversationId:string|undefined;if(typeof body.conversationId==='string'){const owned=await database.select({id:conversations.id}).from(conversations).where(and(eq(conversations.id,body.conversationId),eq(conversations.userId,userId))).limit(1);conversationId=owned[0]?.id;if(conversationId)await database.update(conversations).set({realtimeSessionId:session.sessionId,updatedAt:new Date()}).where(eq(conversations.id,conversationId))}if(!conversationId){const [created]=await database.insert(conversations).values({userId,realtimeSessionId:session.sessionId}).returning({id:conversations.id});conversationId=created!.id}return c.json({...session,conversationId})}catch(error){const e=normalizeError(error);return c.json({ok:false,error:{code:e.code,message:e.message,retryable:e.retryable}},e.status as 500)}});
  app.get('/api/conversations',async c=>{const rows=await database.select({id:conversations.id,status:conversations.status,createdAt:conversations.createdAt,updatedAt:conversations.updatedAt}).from(conversations).where(eq(conversations.userId,c.var.user.id)).orderBy(desc(conversations.updatedAt)).limit(20);return c.json({conversations:rows})});
  app.get('/api/conversations/:id/items',async c=>{const rows=await database.select().from(conversationItems).innerJoin(conversations,eq(conversationItems.conversationId,conversations.id)).where(and(eq(conversations.id,c.req.param('id')),eq(conversations.userId,c.var.user.id))).orderBy(asc(conversationItems.sequence));return c.json({items:rows.map(row=>row.conversation_items)})});
  app.post('/api/conversations/:id/items',async c=>{let body:unknown;try{body=await c.req.json()}catch{return c.json({ok:false,error:{code:'INVALID_REQUEST',message:'Invalid JSON',retryable:false}},400)}const parsed=conversationItemInputSchema.safeParse(body);if(!parsed.success)return c.json({ok:false,error:{code:'INVALID_REQUEST',message:'Invalid conversation item',retryable:false}},400);const id=c.req.param('id');const owned=await database.select({id:conversations.id}).from(conversations).where(and(eq(conversations.id,id),eq(conversations.userId,c.var.user.id))).limit(1);if(!owned[0])return c.json({ok:false,error:{code:'INVALID_REQUEST',message:'Conversation not found',retryable:false}},404);const [item]=await database.insert(conversationItems).values({conversationId:id,sequence:sql`(select coalesce(max(${conversationItems.sequence}), 0) + 1 from ${conversationItems} where ${conversationItems.conversationId} = ${id})`,...parsed.data}).returning();return c.json({item},201)});
  app.post('/api/tools',async c=>{let body:unknown;try{body=await c.req.json()}catch{return c.json({ok:false,callId:'unknown',error:{code:'INVALID_REQUEST',message:'The request body was not valid JSON',retryable:false}},400)}const parsed=toolCallRequestSchema.safeParse(body);if(!parsed.success)return c.json({ok:false,callId:typeof body==='object'&&body&&'callId'in body&&typeof body.callId==='string'?body.callId:'unknown',error:{code:'INVALID_REQUEST',message:'The tool request was invalid',retryable:false}},400);const result=await dispatchTool(parsed.data,{user:c.var.user,requestId:c.var.requestId,database,integrations:{},logger,signal:c.req.raw.signal});return c.json(result,result.ok?200:result.error.code==='UNKNOWN_TOOL'?404:result.error.code==='PERMISSION_DENIED'?403:400)});
  app.onError((error,c)=>{const e=normalizeError(error);logger.error({requestId:c.get('requestId'),errorCode:e.code},'Request failed');return c.json({ok:false,error:{code:e.code,message:e.message,retryable:e.retryable}},500)});
  return app;
}
