import { boolean,index,integer,jsonb,pgEnum,pgTable,text,timestamp,uniqueIndex,uuid } from 'drizzle-orm/pg-core';
// Default-deny RLS and the auth.users FK are maintained in custom migrations
// because the installed Drizzle Kit does not execute pgTable.withRLS.
const timestamps={createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull()};
export const conversationStatus=pgEnum('conversation_status',['active','completed','failed']);
export const itemRole=pgEnum('conversation_item_role',['user','assistant','tool']);
export const executionStatus=pgEnum('tool_execution_status',['running','succeeded','failed','timed_out']);
export const userProfiles=pgTable('user_profiles',{id:uuid('id').primaryKey(),displayName:text('display_name'),...timestamps});
export const conversations=pgTable('conversations',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>userProfiles.id,{onDelete:'cascade'}),realtimeSessionId:text('realtime_session_id'),status:conversationStatus().default('active').notNull(),...timestamps},t=>[index('conversations_user_idx').on(t.userId)]);
export const conversationItems=pgTable('conversation_items',{id:uuid('id').defaultRandom().primaryKey(),conversationId:uuid('conversation_id').notNull().references(()=>conversations.id,{onDelete:'cascade'}),sequence:integer('sequence').notNull(),role:itemRole().notNull(),kind:text('kind').notNull(),transcript:text('transcript'),callId:text('call_id'),payload:jsonb('payload'),completed:boolean('completed').default(false).notNull(),...timestamps},t=>[uniqueIndex('conversation_items_order_idx').on(t.conversationId,t.sequence)]);
export const integrationAccounts=pgTable('integration_accounts',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>userProfiles.id,{onDelete:'cascade'}),provider:text('provider').notNull(),encryptedCredentials:text('encrypted_credentials').notNull(),encryptionIv:text('encryption_iv').notNull(),encryptionTag:text('encryption_tag').notNull(),encryptionKeyVersion:text('encryption_key_version').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}),scopes:text('scopes').array(),...timestamps},t=>[uniqueIndex('integration_user_provider_idx').on(t.userId,t.provider)]);
export const integrationOauthStates=pgTable('integration_oauth_states',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>userProfiles.id,{onDelete:'cascade'}),provider:text('provider').notNull(),stateHash:text('state_hash').notNull(),codeVerifier:text('code_verifier').notNull(),redirectUri:text('redirect_uri').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),consumedAt:timestamp('consumed_at',{withTimezone:true}),...timestamps},t=>[uniqueIndex('integration_oauth_state_hash_idx').on(t.stateHash),index('integration_oauth_state_user_idx').on(t.userId,t.provider)]);
export const toolExecutions=pgTable('tool_executions',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>userProfiles.id),conversationId:uuid('conversation_id').references(()=>conversations.id),requestId:text('request_id').notNull(),callId:text('call_id').notNull(),toolName:text('tool_name').notNull(),status:executionStatus().default('running').notNull(),arguments:jsonb('arguments'),result:jsonb('result'),errorCode:text('error_code'),retryable:boolean('retryable'),durationMs:integer('duration_ms'),...timestamps},t=>[uniqueIndex('tool_execution_idempotency_idx').on(t.userId,t.callId),index('tool_execution_audit_idx').on(t.userId,t.createdAt),index('tool_execution_conversation_idx').on(t.conversationId)]);
